# Generated by Django 3.2.6 on 2021-08-14 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0002_dieter_gym'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.CharField(max_length=10)),
                ('muscle_mass', models.CharField(max_length=10)),
                ('fat_mass', models.CharField(max_length=10)),
                ('percent_body_fat', models.CharField(max_length=10)),
                ('bmi', models.CharField(max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('dieter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.dieter')),
            ],
        ),
    ]
