# Generated by Django 3.2.6 on 2021-08-14 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('record', '0001_initial'),
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='dieter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.dieter'),
        ),
    ]
